version: '3'

services:
  app:
    image: mephit/cats_service:v1.5
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - db

  db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    restart: always
